### ISSUE TITLE
Can't find variable buffer

### ISSUE THREAD

**Issue by romanakash** [stockulus/pouchdb-react-native#109]
I tried both the new and old version of pouchdb-react-native and I get this error saying variable Buffer cannot be found. When I remove the package everything works fine

**Comment by romanakash** [comment]
Temporary fix is to install buffer as a npm dependency and include this code in App.js
`global.Buffer = global.Buffer || require('buffer').Buffer;`

**Comment by romanakash** [comment]
Try to add it on the top of index.js, and make sure sure to clean all the metro cache and watchman modules

**Comment by trojek** [comment]
In react native project created using crna (via expo) I don't have `index.js`.

When I try to install watchman (`npm install -g watchman`) to execute `watchman watch-del-all`, I got a message: `npm WARN deprecated watchman@1.0.0: Package no longer supported. Contact support@npmjs.com for more info.`

I don't know how to clean metro cache.

I try to remove node_modules (`rm -rf node_modules`) and then install all packages (`npm install`), but it doesn't help.

**Comment by romanakash** [comment]
If you weren't already using watchman, you can skip clearing the watchman cache. If you're using expo here's an article about how to reset the cache https://forums.expo.io/t/how-to-clear-the-react-native-packager/1352/12

**Comment by trojek** [comment]
I fixed it by changing npm to yarn... I delete `node_modules` and `package-lock.json`, then install everything using `yarn` and it works.
It works even if I remove: ` global.Buffer = global.Buffer || require('buffer').Buffer;`.
Just magic...

**Comment by romanakash** [comment]
Can confirm works fine without the additional dependency and code

**Comment by chichilatte** [comment]
I tried using yarn instead of npm – `Buffer` still couldn't be found (and yarn created a bunch of duplicate entries in my gradle/MainApplication.java files).

Cleaning the cache also had no effect. My terminal command run from the project folder:
```
rm -r android/app/build/intermediates ; watchman watch-del-all ;  rm -rf $TMPDIR/react-* ; npm start -- --reset-cache
```

Setting the global `Buffer` did work, but only when i replaced...
```
import PouchDB from 'pouchdb-react-native'

```

with...
```
const PouchDB = require('pouchdb-react-native').default
```

Note: our project is using RN 0.56 updated to gradle 4, could be something to do with it.

**Comment by Winglonelion** [comment]
@chichilatte i met same issues with you, and i resolved it with rn-nodeify

> `rn-nodeify` is complete solution for you

**Comment by neilakoh** [comment]
It would be so nice to remove the hassle of using "rn-nodeify" in fixing this issue in the next release.
