### ISSUE TITLE
Filtered replication

### ISSUE THREAD

**Issue by eduardolima93** [stockulus/pouchdb-react-native#12]
Hi,

Does it work with server-side filtering using a design doc filter? I have tried implementing it but with no success.

**Comment by stockulus** [comment]
Hi,

it should work, tested it actually one. Can you provide me an Sample, so that I can check?

**Comment by eduardolima93** [comment]
The problem I'm facing is actually a couchdb bug: https://github.com/pouchdb/pouchdb/issues/1641

If you still have the design document you used when you tested it can you post it here?

Thanks!

**Comment by eduardolima93** [comment]
Never mind, this issue appear only to happen on couchdb on my pc, its working using a cloud service.

**Comment by stockulus** [comment]
currently i just test against express-pouchdb in my node service, but there the Filter looks like

```js
const userFilter = {
  _id: '_design/userEventFilter',
  filters: {
    myfilter: function (doc, req) {
      return doc.userId && doc.userId === req.query.userId
    }.toString()
  }
}
```

but automatic testing is still an issue...
https://github.com/stockulus/pouchdb-react-native/issues/13
