### ISSUE TITLE
HELP Wanted! / Automatic Testing

### ISSUE THREAD

**Issue by stockulus** [stockulus/pouchdb-react-native#13]
Is there somebody here with experience in automatice react-native Testing?

And would like to help?

Thanks!
Christoph

**Comment by ewnd9** [comment]
Hi, I'm playing with running tests from original PouchDB repo in my fork https://github.com/ewnd9/pouchdb-react-native/tree/patch-1 Hopefully will make a pull request soon. 

Unit tests are passing (don't contain adapter logic), integration have following stats:

```
992 passing (4m)
10 pending
112 failing
``` 

Does this approach make sense?

**Comment by stockulus** [comment]
Hi! Thank you!!!

i integrated it into the master brach and changed it to standard.js style.

Seems that there are Problems with the Attachment.

**Comment by ewnd9** [comment]
Could you also enable Travis?

**Comment by stockulus** [comment]
done

**Comment by ewnd9** [comment]
What about other types (integration/map-reduce) of tests in addition to unit?

**Comment by stockulus** [comment]
will follow, currently working on the leveldb less adapter, in order to get them working step by step

**Comment by stockulus** [comment]
-> Can’t automatically merge. Don’t worry, you can still create the pull request.

can you merge all changes i did before, thanks
