### ISSUE TITLE
Possible memory leak when replication set up

### ISSUE THREAD

**Issue by seigel** [stockulus/pouchdb-react-native#14]
When doing a simple test having a local data base replicating to a remote one.  If I just let the app sit there I eventually get a log spit out on the command line:

(node) warning: possible EventEmitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() to increase limit.

**Comment by stockulus** [comment]
Hi Seigel,

can you provide me your setup/code? 
Thanks Christoph

**Comment by JuSeonghyeok** [comment]
Hi, @stockulus.
First of all, thanks for sharing your work.
I am also having same issue as @seigel does.  

The way I tested was running the example app. And I set local couchdb to the sync input.
Initially before the "memory leak problem" error happens, sync works.
'Sync paused' is called several times for a while, then this leads to memory leak problem.

**Comment by stockulus** [comment]
see the Problem Problem with CouchDb (my Projects syncs to a Node.js PouchDB) I'll check out, but can't Promise anything within the next days, because of a jam-packed week and weekend. 

As current workaround you can do "Onetime Syncs" called in setInterval

If you can fixing it, would be great. I'd accept your Pull request.

**Comment by seigel** [comment]
I think I found where some of this is happening.  It might be a core pouchdb problem with replication.

Add code something like this to your pouchdb react native app:

```
var originalOn = EventEmitter.prototype.on;
EventEmitter.prototype.on = function (type, listener) {
    console.log("originalOn", type, this.listeners(type).length, this);
    originalOn(this, arguments);
}

```

You will notice that the number of listeners will grow with time.  I think there might be one more event that exhibits this behaviour.  After editing some source code and watching for a while, I found that one way to reset this behaviour is to just cause a replication to happen.  

This leak has everything to do with how the back off function is implemented.  It keeps adding listeners to the pile.

```
function backOff(opts, returnValue, error, callback) {
  if (opts.retry === false) {
    returnValue.emit('error', error);
    returnValue.removeAllListeners();
    return;
  }
  if (typeof opts.back_off_function !== 'function') {
    opts.back_off_function = pouchdbUtils.defaultBackOff;
  }
  returnValue.emit('requestError', error);
  if (returnValue.state === 'active' || returnValue.state === 'pending') {
    returnValue.emit('paused', error);
    returnValue.state = 'stopped';
    
   // THE CALL BELOW ADDS LISTENERS WITHOUT BOUND WHEN ALL IS QUIET
   
    returnValue.once('active', function () {
      opts.current_back_off = STARTING_BACK_OFF;
    });
  }

  opts.current_back_off = opts.current_back_off || STARTING_BACK_OFF;
  opts.current_back_off = opts.back_off_function(opts.current_back_off);
  setTimeout(callback, opts.current_back_off);
}
```

**Comment by seigel** [comment]
Seems to be a timing thing possibly.  There is a fix in pouch that will avoid the timing badness, but I am still trying to track down the root cause.

**Comment by stockulus** [comment]
Thanks for your help! Hope I find some time this Weekend and will also have a deeper look.

**Comment by stockulus** [comment]
should be fixed in the latest version, but see issue
https://github.com/stockulus/pouchdb-react-native/issues/27
