### ISSUE TITLE
Local database hangs after large syncs (no writedb in Transform class)

### ISSUE THREAD

**Issue by nwlieb** [stockulus/pouchdb-react-native#16]
When syncing from a remote database to a local one, after two batches  (defaults to 100 documents, can use options.batch_size in PouchDB.sync() to change) the local database will hang with the following warning appearing:

Possible Unhandled Promise Rejection (id: 0): no writecb in Transform class

The stack trace of the promise rejection is not very useful so beyond that I'm at a loss. Curiously, you can change batch_size to 1000+ and get more documents through before it fails. 

I've created a minimal test case here: https://github.com/nwlieb/pouch-react-test. This is tested on MacOS with iOS, Windows with android, using both couchdb and pouchdb-server remotes. It has also been tested with live replication and by sequential non-live syncs.

**Comment by stockulus** [comment]
Hi, 

just did
git clone https://github.com/nwlieb/pouch-react-test
cd pouch-react-test
npm install 
node ./node_modules/react-native/local-cli/cli.js run-ios
(CouchDb running in a Docker Container, local, klaemo/couchdb)
(node v6.3.0)

<img width="957" alt="screen shot 2016-07-22 at 12 21 48" src="https://cloud.githubusercontent.com/assets/3983944/17054343/ebf7f66e-5006-11e6-9138-490e34ddf381.png">

<img width="346" alt="demo app" src="https://cloud.githubusercontent.com/assets/3983944/17054261/8c575524-5006-11e6-8103-ced3498b484e.png">

it keeps on Syncing... 

Do i miss something?

Greez Christoph

**Comment by nwlieb** [comment]
Hi, please try increasing the remote docs insert count to 2000 from 300, that should do it. Otherwise, just keep reloading the app and you should see it eventually.
![screen shot 2016-07-22 at 11 59 32 am](https://cloud.githubusercontent.com/assets/6896394/17066332/c91468d8-5003-11e6-8c07-5ed8dd6564e1.png)

Thanks for your great work.

**Comment by stockulus** [comment]
Hi, I can now reproduce the Error, comes from https://github.com/nodejs/readable-stream, just do not know why.

I am currently planning to rewrite the adapter, without all the leveldown simulation; this should solve the issue

**Comment by abelcha** [comment]
Hi @stockulus, Same problem here, when do you think it'll be fixed ?

**Comment by stockulus** [comment]
I have to finish a Project this Week, hope i get some time next week. You could help me with working Testsetup if you want / seen some react-native-mock, already used it in an other Project.

**Comment by abelcha** [comment]
I'll be glad to participate on the project, 
So if i understood correctly, i should create a test-case app with react-native-mock ?

**Comment by stockulus** [comment]
already got help with the test setup, I let you know shortly when i need some help with testing the new version

**Comment by abelcha** [comment]
Ok perfect then, let me know if you need a hand

**Comment by ck-alpha** [comment]
Just to confirm that I am also seeing the error on occasion. Am using pouchdb-react-native with Cloudant and pouchdb-authentication-cloudant. Not exactly sure how to reproduce in my setup. I am replicating a local database to a remote one like the following:

var replicator = PouchDB.replicate(db, remotedb, {
    live: true,
    retry: true
  });

**Comment by ewnd9** [comment]
@ck-alpha What version of `pouchdb-react-native` do you use?

**Comment by ck-alpha** [comment]
It is 5.4.6 @ewnd9

**Comment by stockulus** [comment]
should be fixed in the latest version, but see issue
https://github.com/stockulus/pouchdb-react-native/issues/27
