### ISSUE TITLE
self.constuctor.replicate is not a function

### ISSUE THREAD

**Issue by Jan-Jan** [stockulus/pouchdb-react-native#18]
Thank you for pouchdb-react-native!

When I `react-native run-ios`
```
import PouchDB from 'pouchdb-core'
PouchDB.plugin(require('pouchdb-adapter-asyncstorage').default)
const db = new PouchDB('my_db', {adapter: 'asyncstorage'})

db.replicate.from('http://localhost:5984/my_db', {live: true, retry: true})
```
I get the error `self.constuctor.replicate is not a function`

**Comment by Jan-Jan** [comment]
I've redone the project from scratch: If I instansiated it with
```
import PouchDB from 'pouchdb-react-native'
const db = new PouchDB('my_db')
```
then it all appears to work, but the above error remains.

**Comment by stockulus** [comment]
thinks this is done, when i look at the other issue... Ok?
