### ISSUE TITLE
Received data was not a string, or was not a recognised encoding.

### ISSUE THREAD

**Issue by Jan-Jan** [stockulus/pouchdb-react-native#19]
Thank you for pouchdb-react-native

I've done your basic install, and it looks like I can create a local instance, but when I attempt sync I get warnings to the effect of `Received data was not a string, or was not a recognised encoding`.
If I attempt sync to this DB from other instances it is not a problem though.

**Comment by Jan-Jan** [comment]
This is my code
```
import PouchDB from 'pouchdb-react-native'

const id = 'my_db'
const localDb = new PouchDB(id)
console.log('adapter = '+localDb.adapter)

const remoteId =`http://localhost:5984/${id}`
const remoteDb = new PouchDB(remoteId, {ajax: {cache: false}})

const sync = PouchDB.sync(localDb, remoteDb, {live: true, retry: true})
  .on('error', error => console.error('Sync Error', error))
  .on('change', info => console.log('Sync change', info))
  .on('paused', info => console.log('Sync paused', info))
```

I also get a further repeated warning:
```
Possible Unhandled Promise Rejection (id: 0):
First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
```

**Comment by Jan-Jan** [comment]
Could this have anything to do with me having attachments (type 'image/jpeg') in my db instance? (PS. I setup my db using cradle.)

**Comment by stockulus** [comment]
Could you provide me an Example CouchDB with the Problem? thanks!

**Comment by Jan-Jan** [comment]
With pleasure, where do you normally set something like that up?

**Comment by stockulus** [comment]
you could just attacht the .couch file (/usr/local/var/lib/couchdb) or provide some js code that generates it.

**Comment by Jan-Jan** [comment]
[mammals_of_southern_africa.couch.zip](https://github.com/stockulus/pouchdb-react-native/files/383911/mammals_of_southern_africa.couch.zip)

**Comment by Jan-Jan** [comment]
[db.couch.zip](https://github.com/stockulus/pouchdb-react-native/files/383916/db.couch.zip)

**Comment by stockulus** [comment]
I hope it will get fixed with the new react-native version.

https://github.com/facebook/react-native/commit/08c375f828fd7755b75660c701c70207f3629c6c

**Comment by Jan-Jan** [comment]
Thank you for your effort in helping me.
Lets both hope for v31 :-)
