### ISSUE TITLE
No need to use fs as npm dependency

### ISSUE THREAD

**Issue by YurySolovyov** [stockulus/pouchdb-react-native#20]
Hi!
`fs` is a node core module, there is no need to include it as npm dependency
See https://github.com/npm/npm/issues/13743

**Comment by stockulus** [comment]
just remove did not work, there need to be also code changes in the adapter

**Comment by stockulus** [comment]
would you like to try the beta, it comes without all the leveldown / node dependencies
npm install pouchdb-react-native@next --save

**Comment by YurySolovyov** [comment]
@stockulus sorry, I just created this issue because I found the repo in npm search of `fs` deps, I don't actually use the module.

**Comment by stockulus** [comment]
node / leveldown dependencies removed
