### ISSUE TITLE
Unable to create new databases in >5.4.13

### ISSUE THREAD

**Issue by DanielMaly** [stockulus/pouchdb-react-native#22]
Using any version of pouchdb-react-native later than 5.4.13, the following two lines will cause an error if the created database doesn't exist yet: 

```
PouchDB.plugin(require('pouchdb-adapter-asyncstorage').default)
const localDB = new PouchDB('alice', {adapter: 'asyncstorage'})
```
<img width="374" alt="screenshot 2016-08-26 13 17 44" src="https://cloud.githubusercontent.com/assets/1443921/18003729/d3cac8e2-6b8f-11e6-98ae-a12a72bc2a7d.png">

**Comment by stockulus** [comment]
please stay with 5.4.13 i am working on a version without leveldb, to avoid dependencies with node core packages

**Comment by DanielMaly** [comment]
Ok, please let me know once it's safe to upgrade again.

**Comment by stockulus** [comment]
should work in 5.4.19, please try. Thanks. Sorry for the problems.

**Comment by stockulus** [comment]
would you like to try the beta, it comes without all the leveldown / node dependencies
npm install pouchdb-react-native@next --save

**Comment by DanielMaly** [comment]
I'll try it, thanks! I think it's safe to close this issue now.
