### ISSUE TITLE
Requiring unknown module "util".

### ISSUE THREAD

**Issue by satanmonkey** [stockulus/pouchdb-react-native#23]
I run the example and get a error

android 4.1.2

![screenshot_2016-08-29-16-35-28_com supervision_react_native](https://cloud.githubusercontent.com/assets/8189281/18045976/33eae886-6e08-11e6-9f19-ceef74bb6950.png)

**Comment by stockulus** [comment]
please take 5.4.13 i am working on a version without leveldb, to avoid dependencies with node core packages

**Comment by stockulus** [comment]
should be fixed with 5.4.19, please try

**Comment by satanmonkey** [comment]
I tried to upgrade to 5.4.19 , can run , but pouchdb can not work, the Promise object not fulfilled or rejected

`    const updateDocs = () => {
      localDB.allDocs({include_docs: true, limit: null})
        .then(result => {
		  console.log('allDocs');
          const items = result.rows.map(row => row.doc)
          const ds = new ListView.DataSource({rowHasChanged: (r1, r2) => r1.id !== r2.id})
          this.setState({
            dataSource: ds.cloneWithRows(items),
            count: items.length
          })
        })
        .catch(error => console.warn('Could not load Documents', error, error.message))
    }`

![screenshot_2016-08-30-10-02-21_com example](https://cloud.githubusercontent.com/assets/8189281/18073564/a7b63c0c-6e99-11e6-9256-6c39ffb0a021.png)
![qq 20160830100640](https://cloud.githubusercontent.com/assets/8189281/18073568/b0470c16-6e99-11e6-8d8c-b632f99dbddb.png)

**Comment by josenavarro-famoco** [comment]
I get the same error in the version 6.0.0, with an android device running android 4.4.2

**Comment by stockulus** [comment]
would you like to try the beta, it comes without all the leveldown / node dependencies
npm install pouchdb-react-native@next --save

**Comment by josenavarro-famoco** [comment]
@stockulus It works with that. Thanks
