### ISSUE TITLE
Error in sync with remoteDB, cannot read 'forDocument'

### ISSUE THREAD

**Issue by josenavarro-famoco** [stockulus/pouchdb-react-native#24]
When I try to connect to a remoteDB, i get the following error
Cannot read property 'forDocument' of undefined
I tried to sync in many ways, and i always get the same error.
Any idea why or how can i solve it?

I am using the version @next

**Comment by stockulus** [comment]
there was a bug in the beta ...
update to 6.1.0-beta-7
