### ISSUE TITLE
Flooded by requests on _local documents when doing live replication

### ISSUE THREAD

**Issue by DanielMaly** [stockulus/pouchdb-react-native#30]
In v6, setting up live replication with a remote database results in thousands of requests like GET /_local/yT_xIqhfqh6Aa5f9gahWVg%3D%3D?. Watching the local database for changes is impossible, as there are hundreds of changes to these documents every second. I don't know how the internals of Couch replication work but this didn't happen under v5. Shouldn't _local documents be ignored by replication?

**Comment by stockulus** [comment]
may you try 6.1.10

**Comment by DanielMaly** [comment]
It works great now, thanks!
