### ISSUE TITLE
I'm wondering if this great component supports to sync with parse-server?

### ISSUE THREAD

**Issue by winglight** [stockulus/pouchdb-react-native#31]
I hope it's possible to sync data of pouchdb with parse-server that's the bundle of restful apis. Or should I make an adapter? Any idea would be appreciated.

**Comment by stockulus** [comment]
I do not have experience with "parse-server". I personally do not use the direct Sync of PouchDB, I have a small node service in between handling the changes / user rights etc; reading the changes from pochdb-node + filter + geo logic.

In general the component should sync to PouchDB / CouchDB Http interfaces. If you need an PouchDB adapter for "parse-server" Properly you need to write one.

I Started with the leveldbCode adapter form PouchDb and started developing from there. People at PouchDb are nice and will help if you ask for.

**Comment by ewnd9** [comment]
Take a look at https://github.com/ParsePlatform/parse-server/wiki/Parse-LiveQuery from `parse-server` side and https://pouchdb.com/guides/changes.html from `pouchdb` side.

**Comment by winglight** [comment]
Thanks a lot! I think it's necessary to sync db by manual way to save changed data by change api. And I'm wondering how can I get changed data without any config for remote api?
