### ISSUE TITLE
Storing an attachment fails

### ISSUE THREAD

**Issue by ahaus** [stockulus/pouchdb-react-native#32]
Hi,
I tried to store an attachment as an inline attachment and also tried the db.putAttachment method. But I did not get it working. Also checked your example implementation.

I tried 

```
var attachment = "TGVnZW5kYXJ5IGhlYXJ0cywgdGVhciB1cyBhbGwgYXBhcnQKTWFrZS" +
              "BvdXIgZW1vdGlvbnMgYmxlZWQsIGNyeWluZyBvdXQgaW4gbmVlZA==";
db.putAttachment(doc._id, 'att.txt', doc.rev, attachment, 'text/plain');
```

But it fails with a strange message (Xcode console) 

```
[tid:com.facebook.react.JavaScript] { [ReferenceError: Can't find variable: FileReaderSync]
  line: 133952,
  column: 35,
  sourceURL: 'http://192.168.0.62.xip.io:8081/index.ios.bundle?platform=ios&dev=true&minify=false' }
```

It is the same with inline attachments.
Storing documents without attachments works fine.

Tested with ios: 9.3 (ipad device and iphone 6 simulator).
Did you get storing Attachments working?

**Comment by ahaus** [comment]
Maybe this is related to https://github.com/pouchdb/pouchdb/pull/5687

**Comment by stockulus** [comment]
Hi @ahaus, 

this is related somehow. i guess the setup did not work correctly on your mashine. 

Can you tell me the verion of npm you are using.
where in the node_modules/ folder of the Project is pouchdb-binary-utils?
had you an error / warning after installtion of pouchdb_react_native?

**Comment by ahaus** [comment]
Hi,
npm --version shows:
3.10.3
I am using nodejs 6.6.0.

The module pouchdb-binary-utils is on the same level as all the other pouchdb modules in ./node_modules.

Didn't see errors on installation.

**Comment by ahaus** [comment]
Hi @stockulus,
FYI: I am also experimenting with https://github.com/carbureted/react-native-pouchdb which uses https://github.com/andpor/react-native-sqlite-storage as a websql adapter and a specific version of pouchdb.

**Comment by stockulus** [comment]
hmmm strange... this is working for me... can you check pouchdb-binary-utils / package.json
if there is a section with react-native?

```json
"react-native": {
 "./lib/index.js": "./lib/index.js",
  "./src/base64.js": "./src/base64-browser.js",
 "./src/base64StringToBlobOrBuffer.js": "./src/base64StringToBlobOrBuffer.js",
 "./src/blob.js": "./src/blob.js",
 "./src/binaryStringToBlobOrBuffer.js": "./src/binaryStringToBlobOrBuffer.js",
  "./src/blobOrBufferToBase64.js": "./src/blobOrBufferToBase64.js",
 "./src/blobOrBufferToBinaryString.js": "./src/blobOrBufferToBinaryString.js",
  "./src/typedBuffer.js": "./src/typedBuffer.js"
}

```
if not, add it manually.

This will be added after installation of the pouchdb-react-native packages. If you install different pouchdb packages afterwards, it might get overridden.

Pouchdb currently does not accept the PR pouchdb/pouchdb#5687, so i do not know a better solution to solve it.

**Comment by ahaus** [comment]
Thanks for your help and your fast response.

Did a reinstallation. The installation log doesn't show any errors. Also pouchdb-binary-utils/package.json shows the entries as mention above (without formatting). 

However the error message regarding FileReaderSync still occurs. 

Maybe the package is not loaded correctly. I am using React 0.33.

npm info:
```
npm install pouchdb-react-native --save

> pouchdb-react-native@6.1.14 postinstall /Users/andreas/Development/react-native/BaushotRN/node_modules/pouchdb-react-native
> node ./setup.js

BaushotRN@0.0.1 /Users/andreas/Development/react-native/BaushotRN
└─┬ pouchdb-react-native@6.1.14 
  ├─┬ pouchdb-adapter-asyncstorage@6.1.13 
  │ ├── atob@2.0.3 
  │ ├── blob-polyfill@1.0.20150320 
  │ ├── btoa@1.1.2 
  │ ├─┬ buffer@5.0.0 
  │ │ ├── base64-js@1.2.0 
  │ │ └── ieee754@1.1.6 
  │ ├── events@1.1.1 
  │ ├── left-pad@1.1.2 
  │ ├── pouchdb-adapter-utils@6.0.5 
  │ ├── pouchdb-errors@6.0.5 
  │ ├─┬ pouchdb-md5@6.0.5 
  │ │ └── spark-md5@2.0.2 
  │ ├── pouchdb-merge@6.0.5 
  │ └── pouchdb-utils@6.0.5 
  ├─┬ pouchdb-adapter-http@6.0.5 
  │ ├── argsarray@0.0.1 
  │ ├── es6-promise-pool@2.4.4 
  │ ├── js-extend@1.0.1 
  │ ├─┬ pouchdb-ajax@6.0.5 
  │ │ └─┬ request@2.74.0 
  │ │   ├─┬ form-data@1.0.1 
  │ │   │ └─┬ async@2.0.1 
  │ │   │   └── lodash@4.16.2 
  │ │   └── qs@6.2.1 
  │ ├── pouchdb-binary-utils@6.0.5 
  │ └─┬ pouchdb-promise@6.0.5 
  │   └─┬ lie@3.1.0 
  │     └── immediate@3.0.6 
  ├─┬ pouchdb-core@6.0.5 
  │ ├── pouchdb-collections@6.0.5 
  │ └── scope-eval@0.0.3 
  ├─┬ pouchdb-mapreduce@6.0.5 
  │ ├── pouchdb-collate@6.0.5 
  │ └── pouchdb-mapreduce-utils@6.0.5 
  └─┬ pouchdb-replication@6.0.5 
    ├── pouchdb-checkpointer@6.0.5 
    └── pouchdb-generate-replication-id@6.0.5 

```

**Comment by stockulus** [comment]
Can you try to start the example
git clone https://github.com/stockulus/pouchdb-react-native.git
cd pouchdb-react-native/example
npm install
npm run ios
-> Action Button InsertAttachment

**Comment by ahaus** [comment]
Thanks. I tried the example as state above. Still getting the same error.

Xcode console output:
```
2016-09-29 14:34:37.088 [info][tid:main][RCTBatchedBridge.m:74] Initializing <RCTBatchedBridge: 0x134562cf0> (parent: <RCTBridge: 0x134562340>, executor: RCTJSCExecutor)
2016-09-29 14:34:41.001 [warn][tid:main][RCTEventEmitter.m:54] Sending `websocketFailed` with no listeners registered.
2016-09-29 14:34:41.082 [info][tid:com.facebook.react.JavaScript] asyncstorage
2016-09-29 14:34:41.125 [info][tid:main][RCTRootView.m:239] Running application example ({
    initialProps =     {
    };
    rootTag = 1;
})
2016-09-29 14:34:41.139 [info][tid:com.facebook.react.JavaScript] Running application "example" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
2016-09-29 14:34:41.247 [info][tid:com.facebook.react.JavaScript] 'all pure Items', []
2016-09-29 14:34:50.052 [warn][tid:com.facebook.react.JavaScript] 'save.attachment', { [ReferenceError: Can't find variable: FileReaderSync]
  line: 89929,
  column: 35,
  sourceURL: 'http://192.168.0.62.xip.io:8081/index.ios.bundle?platform=ios&dev=true&minify=false' }
```

**Comment by ahaus** [comment]
One more hint. FileReaderSync is used in the methods 
```
lib/index.js
src/ReadAsArrayBuffer.js
src/ReadAsBinaryString.js
```

**Comment by ahaus** [comment]
I tracked the problem down. There is a type mismatch in node_modules/pouchdb-binary-utils/lib/index.js with the function readAsArrayBuffer().

It assumes a Blob as an argument however the value given in the argument is of type Uint8Array which causes a problem with reader.readAsArrayBuffer(blob);

**Comment by stockulus** [comment]
can not find the problem that quickly, seems something changed in PouchDB.. properly i have some time tomorror

**Comment by ahaus** [comment]
Hi,
got it working (workaround) for Base64 strings but not for Blobs yet. 

The problem is in pouchdb-adapter-asyncstorage/bulk_docs.js using wrong data types. 
1. It calls the function readAsArrayBuffer() in pouchdb-binary-utils/lib/index.js with Uint8Array and not using a Blob as expected (called from binaryMd5()) 
2. global.btoa(binData) throws an error if the base64 contains non latin1 characters

I added a check for Blob in pouchdb-binary-utils/lib/index.js in the function readAsArrayBuffer(), line 61 ff. since a Uint8Array is used and not a Blob
```
function readAsArrayBuffer(blob, callback) {
  if (typeof FileReader === 'undefined') {
    // fix for Firefox in a web worker:
    // https://bugzilla.mozilla.org/show_bug.cgi?id=901097
    return callback(new FileReaderSync().readAsArrayBuffer(blob));
  }

  if (blob instanceof Blob) {
    var reader = new FileReader();
    reader.onloadend = function (e) {
      var result = e.target.result || new ArrayBuffer(0);
      callback(result);
    };
    reader.readAsArrayBuffer(blob);
  }
  else {
    callback(blob.buffer);
  }
}
```

I also did a change in pouchdb-adapter-asyncstorage/bulk_docs.js since the method global.btoa(binData) throws an error if special characters are within the base64 or reading handling image data.
Error message with global.btoa(binData):
`DOMException: Failed to execute btoa on WorkerGlobalScope: The string to be encoded contains characters outside of the Latin1 range.`

I just use the already available base64 string.

Change in bulk_docs.js:

```
...
              const dbAttachment = [
                forAttachment(meta.digest), {
                  digest: meta.digest,
                  content_type: meta.content_type,
                  data: (typeof attachment.data === 'string') ?  attachment.data : global.btoa(binData) //global.btoa(binData)
                }]
              resolve({attachment: meta, dbAttachment})
...
```
I think this type checks and conversion have to be done properly in bulk_docs.js that there are no changes necessary in pouchdb-binary-utils.

Hope this helps a bit for further investigation.

**Comment by ahaus** [comment]
Just for info: 
Others might ran in the storage limitation of Android. On Android asyncstorage has a limitation of 6 MB per default. I am also temporarily storing images for synchronization in PouchDB so this limit is reached very quickly. I overcome this by setting the maximum size when starting the app in MainApplication.getPackages() using

`long size = 50L * 1024L * 1024L;   // 50 MB   com.facebook.react.modules.storage.ReactDatabaseSupplier.getInstance(getApplicationContext()).setMaximumSize(size);`

**Comment by stockulus** [comment]
found the other Bug, just not sure how to find good solution...
Will Take the Storage Note into the readme

**Comment by stockulus** [comment]
@ahaus there is a new Version 6.1.15 out right now. It is not using the pouchdb_md5 anymore, makes it simpler

**Comment by ahaus** [comment]
Hi,
thanks for the update. Just wanted to let you know that setup.js fails on node 5.x (let not supported). It works on node 6.x

```
Andreas-Hausleitners-MacBook-Pro:BaushotRN andreas$ npm install --save pouchdb-react-native

> pouchdb-react-native@6.1.16 postinstall /Users/andreas/Development/react-native/BaushotRN/node_modules/pouchdb-react-native
> node ./setup.js

/Users/andreas/Development/react-native/BaushotRN/node_modules/pouchdb-react-native/setup.js:3
let PATH = './node_modules/pouchdb-binary-utils/package.json'
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/andreas/.nvm/versions/node/v5.11.1/bin/node" "/Users/andreas/.nvm/versions/node/v5.11.1/bin/npm" "install" "--save" "pouchdb-react-native"
npm ERR! node v5.11.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! pouchdb-react-native@6.1.16 postinstall: `node ./setup.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pouchdb-react-native@6.1.16 postinstall script 'node ./setup.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pouchdb-react-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./setup.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pouchdb-react-native
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pouchdb-react-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andreas/Development/react-native/BaushotRN/npm-debug.log
Andreas-Hausleitners-MacBook-Pro:BaushotRN andreas$ nvm


```

**Comment by ahaus** [comment]
The issue with global.btoa(binData)  (bulk_docs.js, line 69) still exists and throws an error if the base64 encoded attachment (e.g. images) contains non latin1 characters. I changed line 69 as shown below since I already have the base64 encoded string in attachment.data and do not need to convert again. You will be able to reproduce the problem if you change the example base64 encoded string in example/app.js, line 65 with one containing special characters (e.g. äöü€ ...)

```
bulk_docs.js, line 61: const data = global.btoa(binData)
to
bulk_docs.js, line 61: const data = attachment.data
```

**Comment by stockulus** [comment]
If you want just create a pull request:)
