### ISSUE TITLE
Does downloading attachments work?

### ISSUE THREAD

**Issue by cmrichards** [stockulus/pouchdb-react-native#34]
Have you managed to download attachments with this library?   I'm trying all the different methods:  getAttachment,  and get(..., {attachments: true}), allDocs(.., { attachments: true})  but all I ever see is an empty string in the data field.  

I'm not having any issues with saving and syncing attachments - that works just fine.

**Comment by stockulus** [comment]
Hi,

there can be still some issues with attachments, because i currently do not use them in my app. If you can provide a Sample that demonstrates the Problem (as Pull Request in the Example Project) that will help me debugging the issue

Christoph

**Comment by stockulus** [comment]
Contributors also welcome ;)

**Comment by ddolheguy** [comment]
Unfortunately I too can confirm that attachments don't work with this library (downloading from a source CouchDB I mean)....  Hoping this gets fixed soon as it's a shop stopper for me on this one.

**Comment by stockulus** [comment]
There is now work on attachments, will be coordinated with Issue:
https://github.com/stockulus/pouchdb-react-native/issues/68
