### ISSUE TITLE
any plan to integrate pouchdb-find plugin

### ISSUE THREAD

**Issue by ymote** [stockulus/pouchdb-react-native#35]
pouchdb-find is super nice to have

**Comment by ewnd9** [comment]
Please elaborate.
If I recall it correctly, `pouchdb-find` works on the top of `pouchdb`, there is no need to integrate it.

**Comment by stockulus** [comment]
You can easily just create your own bundle, more infos under 
https://pouchdb.com/2016/06/06/introducing-pouchdb-custom-builds.html

in general I'd like to keep the Default pouchdb-react-native bundle as small as Possible.

Sample Bundle could look like... make it Public if you want.

```js
'use strict'

import PouchDB from 'pouchdb-core'
import AsyncStoragePouch from 'pouchdb-adapter-asyncstorage'
import HttpPouch from 'pouchdb-adapter-http'
import mapreduce from 'pouchdb-mapreduce'
import find from 'pouchdb-find'
import replication from 'pouchdb-replication'

PouchDB
  .plugin(AsyncStoragePouch)
  .plugin(HttpPouch)
  .plugin(mapreduce)
  .plugin(find)
  .plugin(replication)

export default PouchDB
```

Christoph

**Comment by ewnd9** [comment]
@stockulus Actually, the order doesn't matter and plugins could be applied at any time, so it could be simply:

```js
'use strict'

import PouchDB from 'pouchdb-react-native'
import find from 'pouchdb-find'

PouchDB
  .plugin(find)

export default PouchDB
```

**Comment by Guilleanto** [comment]
Following the advice I find this error in the log

Can't find variable: self

similar to this image

![image](https://user-images.githubusercontent.com/18471149/155039710-29a76627-ad71-4a40-990d-246c2a179749.png)
