### ISSUE TITLE
Install fails on node 4.x

### ISSUE THREAD

**Issue by dendrochronology** [stockulus/pouchdb-react-native#36]
As @ahaus mentioned in [issue 32](https://github.com/stockulus/pouchdb-react-native/issues/32#issuecomment-250929260), install fails on stable node (4.x), due to unsupported use of `let`.

**Comment by ahaus** [comment]
This is related to node 4.x and node 5.x. "let" for variable definitions is supported by node 6.x. I would recommend to use "var" instead of "let" for better compatibility by now.

**Comment by stockulus** [comment]
it should be fixed now (6.1.17). I am not sure if this installation "hack" is working with npm2, it works with npm3.

**Comment by ewnd9** [comment]
The script won't work on npm@2, see https://github.com/stockulus/pouchdb-react-native/pull/37

Also `let` is available in `strict` mode in node@4

**Comment by stockulus** [comment]
https://github.com/pouchdb/pouchdb/pull/5687
This is the only reason, for this setup hack.

so the solution should be to replace all pouchdb-binary-utils package.json files

**Comment by stockulus** [comment]
https://github.com/stockulus/pouchdb-react-native/issues/51
