### ISSUE TITLE
Pull Replication fails sporadically

### ISSUE THREAD

**Issue by blairio** [stockulus/pouchdb-react-native#38]
We had a big problem replicating with a remote CouchDB Server.
It wasn't 100% all the time, but most of the time the replication would continuously throw an undefined exception here: https://github.com/stockulus/pouchdb-react-native/blob/master/packages/pouchdb-adapter-asyncstorage/src/asyncstorage_core.js#L53

Also, we had a problem with conflict resolution. Sometimes the client would pick the wrong revision as the winner. It would not pick the revision that other clients picked. Also, the conflict list would contain the same revision that was picked. The other revision (that should have won) would only be available in the open_revs list. Not sure if these issues are related.

**Comment by stockulus** [comment]
Hi,

can you help me to reproduce the error, i have no clue where to look. What are the values of keys in this case? There was also a new release of pouchdb just arrived here. There where some nodes about replication.

Christoph

**Comment by ewnd9** [comment]
> Also, we had a problem with conflict resolution. Sometimes the client would pick the wrong revision as the winner. It would not pick the revision that other clients picked. Also, the conflict list would contain the same revision that was picked. The other revision (that should have won) would only be available in the open_revs list. Not sure if these issues are related.

@blairio https://github.com/stockulus/pouchdb-react-native/pull/41 hopefully fixes that, try a new version, please.

**Comment by stockulus** [comment]
reopen if still is an issue
