### ISSUE TITLE
Document I can see in remote couchdb, does not show up in alldocs after syncing

### ISSUE THREAD

**Issue by JDeuce** [stockulus/pouchdb-react-native#40]
Just starting to debug this issue that has happened sporadically to me in an app I'm working on using this plugin.

I have a basic app using this with a few documents, that syncs to a remote CouchDB instance.

Right now I have a document with ID '2016-11-2' that doesn't show up in alldocs on PouchDB, even though it's there on the remote server. PouchDB reports the sync was successful, and other types of changes are still flowing correctly back and forth.

If I hit the CouchDB changes API manually I get an entry like this for the document '2016-11-2', which appears like there is a conflict:

    {
      "seq":41,
      "id":"2016-11-2",
      "changes":[
        {"rev":"1-1b2b09d47ea243554a79d7b3af29a811"},
        {"rev":"7-ce1394ede863930bd45746f8bd1f933e"}
      ]
    }

Using couch API, or futon, to fetch that document, selects rev 1-1b2b09d47ea243554a79d7b3af29a811 as the winner and I get a response like this:

    {
      "_id":"2016-11-2",
      "_rev":"1-1b2b09d47ea243554a79d7b3af29a811",
      "foo": "bar"
     }

If I specifically fetch the other rev, it comes up deleted:

    {
      "_id":"2016-11-2",
      "_rev":"7-ce1394ede863930bd45746f8bd1f933e",
      "_deleted":true
     }

Dumping the keys in AsyncStorage got me this,  which appears like something has caused PouchDB to select the other, deleted revision, as the winner:

Storage Key | Value
--------------|--------
my-app!ÿby-sequenceÿ0000000000000017 | {"foo":"bar","_id":"2016-11-2","_rev":"1-1b2b09d47ea243554a79d7b3af29a811"}'
my-app!ÿby-sequenceÿ0000000000000018 | {"_id":"2016-11-2","_rev":"7-ce1394ede863930bd45746f8bd1f933e"}
 my-app!ÿdocument-storeÿ2016-11-2 | {"id":"2016-11-2","rev":"7-ce1394ede863930bd45746f8bd1f933e" ...}

So then later when I do the all docs, it considers the doc deleted and won't include it.

Is this a bug in the AsyncStorage driver or am I doing something wrong?

**Comment by ewnd9** [comment]
Could you try to reproduce it locally (in terminal, not on a device/emulator) with `react-native-mock`, please?

```json
{
  "private": true,
  "scripts": {
    "start": "babel-node index"
  },
  "dependencies": {
    "babel-cli": "^6.18.0",
    "babel-preset-react-native": "^1.9.0",
    "pouchdb-react-native": "^6.1.20",
    "react": "^15.3.2",
    "react-native": "^0.36.1",
    "react-native-mock": "^0.2.7"
  }
}
```

```js
// index.js
'use strict';

require('babel-register')({
  presets: ['react-native'],
  ignore: path => {
    return path.indexOf('pouchdb') === -1 && path !== (__dirname + '/app.js');
  }
});

require('./app');
```

```js
// app.js
import 'babel-polyfill';
import 'react-native-mock/mock';
import PouchDB from 'pouchdb-react-native';

(async () => {
  const db = new PouchDB('mydb');
  const doc = await db.put({ _id: '1', foo: 'bar' });
  console.log(await db.get('1'));
})();
```

**Comment by JDeuce** [comment]
Hmm yeah thanks for the framework for testing. I'll try and get a better repro. I'm still not 100% sure how I've caused it even.

**Comment by JDeuce** [comment]
I was able to reproduce a similar type of error in the playground, see my fork
https://github.com/JDeuce/pouchdb-react-native-playground/commit/28a82ef96c9bc9d07dc969d8eb51bc683ad7bc3b

I basically just introduce a simple conflict by inserting a document with the same ID into 2 local databases, 
and then replicate it to a local PouchDB, and to a remote CouchDB.

My expectation is that after syncing in the same manner,  the local PouchDB destination would match the remote CouchDB destination. However, in some cases they are selecting different winners.

Here is the run output from 2 separate runs:
https://gist.github.com/JDeuce/40e590604af9637dbf00de764094262c

In the first run, they select the same winning conflict, but in the second run they select different ones.

Run it like

npm start -- http://myserver.com:5984/test

**Comment by ewnd9** [comment]
Could you also add assertions with any assertion library like [`assert`](https://github.com/defunctzombie/commonjs-assert), please? Sorry for not clarifying it in the first message

**Comment by JDeuce** [comment]
Here's another test case with some assertions. I was also able to replicate the issue this time with local databases only.

https://github.com/JDeuce/pouchdb-react-native-playground/commit/7f341d1e27784b7f56d2badc8d20464351de9929

It seems like the winning rev is being determined by the order that replication happens, when it should happen deterministically based on the rev ids of the document.

**Comment by JDeuce** [comment]
Here is the same test with the basic browser version of PouchDB in jsfiddle:

https://jsfiddle.net/s3aoc8a3/

The rev ids are consistent every time.

Feels like this is a definite issue in pouchdb-react-native.

Let me know thoughts.

**Comment by ewnd9** [comment]
Send a pull request #41 Hopefully it doesn't break anything beyond what is under the tests now

@stockulus Have you had a chance to look at the issue?
