### ISSUE TITLE
Problem to install 

### ISSUE THREAD

**Issue by laurindo** [stockulus/pouchdb-react-native#47]
I'm  trying install pouchdb-react-native, but it's happened a problem with my installation.

Node v4.2.5
npm  v2.14.12

![screenshot 2016-12-17 10 32 52](https://cloud.githubusercontent.com/assets/2501144/21287185/868ee47e-c444-11e6-8efe-9c7501b9060d.png)

**Comment by laurindo** [comment]
Problem resolved with node 5.0.0

**Comment by ddolheguy** [comment]
It's not a node issue.  You should use npm 3+ for all React Native development.

**Comment by stockulus** [comment]
https://github.com/stockulus/pouchdb-react-native/issues/51
