### ISSUE TITLE
pre-filled database

### ISSUE THREAD

**Issue by arpecop** [stockulus/pouchdb-react-native#48]
I'dd appreciate an example of PDB pre-installed database, do we have to use sqlite plugin?

**Comment by ewnd9** [comment]
You could try to use https://github.com/nolanlawson/pouchdb-load to load from a device filesystem.

The general rule of thumb is that pretty much anything from pouch ecosystem should work.

**Comment by arpecop** [comment]
Is it possible in the path of development  with the testing device to pre-fill the database and avoid slowdowns with the end-user device
 new PouchDB('./mydb.db', 
how does absolute paths work in that scenario , I remember tested that before and no /mydb.db was not generated/visible on the project folder
Thanks

**Comment by jaredly** [comment]
@arpecop you might want to look at https://github.com/johanneslumpe/react-native-fs or something if you're trying to load something from the filesystem.
