### ISSUE TITLE
Bulk_Doc error in replication for _deleted docs

### ISSUE THREAD

**Issue by ddolheguy** [stockulus/pouchdb-react-native#49]
After a lot of debugging, I found a major issue with the Bulk_Docs file, in relation to filtered replication.

Specifically:
https://github.com/stockulus/pouchdb-react-native/blob/master/packages/pouchdb-adapter-asyncstorage/src/bulk_docs.js#L132-L135

When updating the document marked with ```_deleted: true``` all properties on the document except the ```_id, _rev and _deleted``` are removed which is wrong as filtered replication required which ever fields the query is working upon.

**Comment by stockulus** [comment]
https://github.com/stockulus/pouchdb-react-native/pull/50
