### ISSUE TITLE
Installation fails with npm2

### ISSUE THREAD

**Issue by stockulus** [stockulus/pouchdb-react-native#51]
Installation via npm 2 fails.

See also:
https://github.com/stockulus/pouchdb-react-native/issues/47
https://github.com/stockulus/pouchdb-react-native/issues/36

Reason:
https://github.com/pouchdb/pouchdb#5687

**Comment by ewnd9** [comment]
@stockulus Why did you close #37 without any comment? I believe prior work may help if someone would decide to fix that

**Comment by stockulus** [comment]
reopened it, do not believe someone will fix it, I won't

**Comment by ddolheguy** [comment]
Personally I would close this as well since the majority of React-Native libs require npm 3+ and hence I would just make this a base requirement.  Agree I can't see this being fixed.

**Comment by rodrigoelp** [comment]
Given the trail of this issue, and the fact most people do react native on node 6 or 8... I would close it as won't fix.
