### ISSUE TITLE
Websql throws an error when Remote js debug disabled

### ISSUE THREAD

**Issue by prasad-ksrd** [stockulus/pouchdb-react-native#54]
Hi 

Hope you are doing good.I need a help from you

var db = new PouchDB('test');
var rdb = new PouchDB('https://XXXXX.cloudant.com/test', {skipSetup: true});

How to Sync two database withpout websql..If websql is the only way means how it will work in android application if remote js debug disabled?

Please advise

**Comment by stockulus** [comment]
Hi,

have you tried the sample Application?

It should not require any remote debugging.
