### ISSUE TITLE
endless loop in "npm install"

### ISSUE THREAD

**Issue by derkaan** [stockulus/pouchdb-react-native#55]
I followed the installation instructions from the readme, but it looks like that the command npm install runs into an endless loop.

These are the followed commands:

```
git clone https://github.com/stockulus/pouchdb-react-native.git 
cd pouchdb-react-native
npm install # this one runs for ever
npm test
cd example
npm run ios

```
My used npm version is 4.1.2

**Comment by stockulus** [comment]
Hi,

npm install takes a while, because it does the install of pouchdb as well.

Just tried it again, but i can not see the Problem you report.

Greez
  Christoph

**Comment by jurassix** [comment]
I experience this same problem, it was due to the `pouchdb-original` submodule was missing. Once you clone the submodule the issue is resolved.

**Comment by stockulus** [comment]
thanks for that hint, just updated the readme
