### ISSUE TITLE
So what about attachments now? 

### ISSUE THREAD

**Issue by tseck** [stockulus/pouchdb-react-native#57]
Hi there,

so I've tried the attachments and am getting a ETIMEDOUT-Error on getAttachments(..) and the attachments are not downloaded/synced automatically.
I am syncing the remote to the local db and getting the documents with db.allDocs({include_docs: true, limit: null, attachments: true}), still no attachments.
Via curl it goes, it can download attachments.

Is there anything else I would need to do, like adding attachments: true to the sync-command or should this be functioning then?

I have about 300 attachments á 20kb each.

Running version 6.1.2 of pouch and 6.1.26 of pouchdb-react-native.

Do I have to set any CORS or alike?

Or are attachments still not recommended (even only those some MB of data which is, sorry, but ridiculous nowadays)?

People are spending lot of time trying to implement this possibly wasted.

Regards

**Comment by stockulus** [comment]
Hi,

sorry for the inconvenience. I know that there are still Problems with Attachments, but i did not find private time to investigate more. My Current Projects do not need attachments, and I don't get paid for this package.

If you want to fix that, please go ahead, PR and help is welcome.

Thanks
  Christoph

**Comment by der-ede** [comment]
@stockulus , 

thank you, no problem, I just thought someone might know.

**Comment by der-ede** [comment]
I know its all open source, its just that since people are using it and sacrifice time for it it would be convenient to state what the library can offer and where the limitations are.

**Comment by stockulus** [comment]
I updated the readme

**Comment by der-ede** [comment]
thank you

**Comment by der-ede** [comment]
and also hi from Darmstadt :)

**Comment by stockulus** [comment]
There is now work on attachments, will be coordinated with Issue:
https://github.com/stockulus/pouchdb-react-native/issues/68
