### ISSUE TITLE
pouch-find & create index

### ISSUE THREAD

**Issue by mlecoq** [stockulus/pouchdb-react-native#70]
I have added pouch-find in my project in order to be able to make find queries (last pouchdb version embed pouch-find but no the one used in pouchdb-react-native).

Find queries work well but 
When I want to create a simple index 

```
db.createIndex({
  index: {
    fields: ['customer']
  }
})
```

My app crashes (without any log)

**Comment by stockulus** [comment]
Can you provide me an sample project, that I can npm install
npm run ios
Greez Christoph

**Comment by mlecoq** [comment]
You can close this one. I was not able to build an example and after erase of pouchdb database everything worked fine. It was in a strange state.
