### ISSUE TITLE
Pouchdb.default is not accepting the prefix option

### ISSUE THREAD

**Issue by frangeris** [stockulus/pouchdb-react-native#72]
Thanks for this bridge :]

I'm having some issues trying to specify the path for the db file, first I thought that could be related to the adapter, because by default is using `asyncstorage` and in (API References)[https://pouchdb.com/api.html#overview] says:

> In IndexedDB and WebSQL, PouchDB will use _pouch_ to prefix the internal database names. Do not manually create databases with the same prefix.

So I tried installing the `pouchdb-adapter-idb` and retry passing the prefix in `options`, but is not creating the db file.

```javascript
    PouchDB.plugin(require('pouchdb-adapter-idb'))
    let db = PouchDB.defaults({
      prefix: `${fs.MainBundlePath}/embeded/public/`
    })

    // I even try setting it directly
    db.prefix = `${fs.MainBundlePath}/embeded/public/`

    let test = new db('mydb', {adapter: 'idb'})

    console.log(fs.MainBundlePath, test)
```
<img width="734" alt="screen shot 2017-06-26 at 10 35 53 pm" src="https://user-images.githubusercontent.com/811381/27567087-e56369b8-5abf-11e7-9116-1f96b639150d.png">

**Note** `__pouch__` in the `prefix`.

Where is the issue?

Thanks...

_**ps: I can write in that path, tested**_

**Comment by stockulus** [comment]
Hi @frangeris,

pouchdb-react-native is not supporting any prefix now. All Data is written to the AsyncStore.

"On iOS, AsyncStorage is backed by native code that stores small values in a serialized dictionary and larger values in separate files. On Android, AsyncStorage will use either RocksDB or SQLite based on what is available."
https://facebook.github.io/react-native/docs/asyncstorage.html

But still you can have different Databases with different Names. 

```js
import { AsyncStore } from 'react-native'

AsyncStore.getAllKeys().then(key => console.warn(key))
```

you can see how it is organized internally. (after you created Databases and docs)

Christoph

**Comment by frangeris** [comment]
Any way to access to the db file? I'm interested in use the database file from an embedded app inside the mobile app, but how can I specify where the file should be saved?

Thanks,

**Comment by stockulus** [comment]
not sure, you should have a look in the AsyncStorage Specs and implementation (of react_native) and it is different each Platform

**Comment by frangeris** [comment]
Thanks @stockulus
