### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by reutopiaer** [stockulus/pouchdb-react-native#73]
ERROR in ./node_modules/pouchdb-adapter-asyncstorage/src/all_docs.js
Module parse failed:  node_modules/pouchdb-adapter-asyncstorage/src/all_docs.js Unexpected token (40:8)
|     if (includeDoc && !doc.deleted) {
|       result.doc = {
|         ...doc.data,
|         _id: doc.id,
|         _rev: doc.winningRev

**Comment by stockulus** [comment]
?

can you provide a sample that produces this Error?

**Comment by reutopiaer** [comment]
https://github.com/pubkey/rxdb/blob/master/examples/react-native/src/index.js line25 RxDB.plugin(require('pouchdb-adapter-asyncstorage').default);
Sorry,I'm a new learner. I just run this demo.

**Comment by reutopiaer** [comment]
webpack config error

**Comment by sm2017** [comment]
@reutopiaer I have same issue , How you solve it?

Can you share webpack config?
