### ISSUE TITLE
PouchDB remote instance not taking new params

### ISSUE THREAD

**Issue by kkbhav** [stockulus/pouchdb-react-native#75]
When I try to assign new authentication parameters to remote pouchdb, Pouch does not use new params and keep syncing using old authentication parameters. Can you please look into this issue and let me know if it is from my side or something is wrong inside.

For eg
remote = new PouchDB(http://user1:pass1@pouch.com
remote = new PouchDB(http://user1:pass2@pouch.com

PouchDB.replicate(remote, local) ===> uses pass1 instead of pass2

**Comment by stockulus** [comment]
Hi,

this might be not related to this package, because it is just using the http adapter of the pouchDB, but i have currently no time for deeper investigation.

in any case it would be good to have a Project / Test Case that demonstrates the Issue.

Christoph
