### ISSUE TITLE
Error: Invalid Adapter: http

### ISSUE THREAD

**Issue by radiegtya** [stockulus/pouchdb-react-native#77]
I am using RN 0.47.1. This error happened when I am initialize remoteDB.

here is my code:
```javascript
constructor(){
    super();

    this.db = new PouchDB('post', {adapter: 'asyncstorage'})

   //this line cause error
    this.remoteDB = new PouchDB('http://localhost:5984/post', {ajax: {cache: false}})

    this.db.sync(this.remoteDB)

    this.state = {
      results: []
    }
  }
```

Please help

**Comment by stockulus** [comment]
Hi,

Did you try out the example Project, if it is working there for you?

Christoph

**Comment by radiegtya** [comment]
Sorry it was my mistake. 

But maybe you should update the doc..

I am wrong importing "pouchdb-core" rather than "react-native-pouchdb"

**Comment by radiegtya** [comment]
Yea its working but the sync not work as expected. Need multi refresh to get synced data
