### ISSUE TITLE
Create typescript definitions

### ISSUE THREAD

**Issue by shadowmynd** [stockulus/pouchdb-react-native#81]
No typescript definitions exist which makes it less desirable from a hotswap perspective with pouchdb proper when using the compilerOptions.noImplicitAny setting.

**Comment by stockulus** [comment]
I do not use typescript at all, but if you do a pull request that adds the type definitions, I'll accept it and publish them

**Comment by rodrigoelp** [comment]
Hi @stockulus, I've created the type definition for the library... here: #87

**Comment by rodrigoelp** [comment]
Given the pull request was merged and accepted, I think this issue should be closed.
