### ISSUE TITLE
PouchDB find is not a function

### ISSUE THREAD

**Issue by ozmaat** [stockulus/pouchdb-react-native#91]
It is mentioned [here](https://github.com/stockulus/pouchdb-react-native/issues/35) that we can create a custom build with plugins. 

But  [pouchdb-find plugin](https://github.com/nolanlawson/pouchdb-find) has been moved to pouchDB  and it is not listed in pouch [plugins page](https://pouchdb.com/external.html) anymore.

When I use the find, "find is not a function" error is thrown. What is the recommended way to integrate find module in this case? 

Thank you

**Comment by ozmaat** [comment]
@ccfiel  - I am not using the find plugin at the moment but at that time I have manually added the pouchdb-find (version 6.4.3) under node_modules from https://github.com/pubkey/rxdb. And It worked.

**Comment by ccfiel** [comment]
thanks @ozmaat !

**Comment by krishna-404** [comment]
So is there any way to use pouchdb-find or we need to just start using RxDB?
