### ISSUE TITLE
Does pouchdb-react-native support additional plugins?

### ISSUE THREAD

**Issue by greenais** [stockulus/pouchdb-react-native#94]
Hi, 
My setup requires client authentication on CouchDB side and https.
According to docs pouchdb-react-native contains replication, HTTP and map/reduce plugins only.

In case I need .login plugin to get client authentication - could I :
1. require it within pouchdb-react-native module (if so 
 a) which way?
 b) is AsyncStorage 6 MB limit already fixed there?) 
or 
2. the only way to attach additional plugins it is to proceed with pochdb-core + pouchdb-adapter-asyncstorage?

BTW, it isn't clear from docs which file (I assume in android folder, right?) and which particular part of that file should be modified to fix 6MB limit. Some tiny clarification could be really helpful.

And let me thank you author for the great job on this module, awesome.

**Comment by stockulus** [comment]
'use strict'

import PouchDB from 'pouchdb-react-native‘

PouchDB
  .plugin(YourPlugIn)

export default PouchDB

**Comment by stockulus** [comment]
The android fix, is not applied automatically

**Comment by greenais** [comment]
Thank you. I've attached authentication plugin - it works as expected.

Any clue regarding exact file to apply android fix in, then?

**Comment by stockulus** [comment]
https://codedaily.io/tutorials/4/Increase-Android-AsyncStorage-Size-in-React-Native

**Comment by greenais** [comment]
Thank you!
