### ISSUE TITLE
Upgrade codebase to use Prettier

### ISSUE THREAD

**Issue by jurassix** [stockulus/pouchdb-react-native#95]
@stockulus are you open to removing the current _standard.js_ formatting rules and replacing with [Prettier](https://github.com/prettier/prettier)? 

One of the harder parts of contributing to this code base was cleaning up the codebase to match standard, while many of the rules can be automatically fixed the developer workflow was pretty slow for me. 

We could do the migration as a single shot, add the new dependencies, format the source, and add some commit hooks to format commits to apply the Prettier rules going forward.

**Comment by stockulus** [comment]
.prettierrc like
```
{
  "printWidth": 80,
  "tabWidth": 2,
  "singleQuote": true,
  "trailingComma": "none",
  "bracketSpacing": true,
  "semi": false,
  "useTabs": false,
  "jsxBracketSameLine": false,
  "proseWrap": "never"
}
```
I would be totally fine

**Comment by jurassix** [comment]
Cool, I'll open a PR with this proposal for you to review.
